### ISSUE TITLE
Feature Request: Password Recovery Functionality

### ISSUE THREAD

**Issue by Inyong-Hwang** [JunheePark0224/Pluna#26]
**Request**
- Currently, there is no way for users to recover their account if they forget their password. This could lead to frustration and potential loss of users who are unable to access their accounts.

*Proposed Solution
Add a "Forgot Password" feature to the login page. This feature should:

1. Provide a link or button labeled "Forgot Password" on the login page.
2. Allow users to enter their registered e-mail address.
3. Send a password through individual e-mail.

*Benefits
- Improves user experience by offering a way to regain access to accounts.
Enhances the web's usability and professionalism.
Reduces support requests related to account recovery.

Expected Outcome
Users will be able to find their passwords quickly and easily, leading to better user retention and satisfaction.

**Comment by kwonjaeuk** [comment]
This is a great idea, and thank you for contributing such a thoughtful solution! It will greatly enhance user experience by making account recovery easier and more accessible.

**Comment by JunheePark0224** [comment]
Yeah, I think it is definitely one of the necessary functions to be better websites!! Let's add that function: )
