### ISSUE TITLE
Refactor Steps for Improved User Input Experience

### ISSUE THREAD

**Issue by JunheePark0224** [JunheePark0224/Pluna#35]
# Refactor Steps for Improved User Input Experience

## Description
We aim to enhance the structure and usability of our multi-step input process by reorganizing the content and providing clear distinctions between required and optional information.

---

### Step 1: Necessary Information (Subjects)
- Retain the current fields:
  - **Subject**
  - **Range** (e.g., Math I, II)
  - **Difficulty** (e.g., Easy, Hard)
  - **Study Hours** (e.g., 2 hours per day)
- **Mandatory Step**: All fields must be filled out before moving to Step 2.
- Add a message at the top of the page:  
  > `"All fields are required to proceed to the next step."`

---

### Step 2: Optional Information for Subjects
- Update fields to collect subject-specific details:
  - **Exam Date** (e.g., "2024-12-10")
  - **Subject-Specific Notes** (e.g., "I don't want to study this subject on Saturdays.")
    - Increase the input field size to allow for longer text input, as this field may require users to write detailed notes.
- **Optional Step**: Users can proceed without completing all fields.
- Add a message at the top of the page:  
  > `"This step is optional. You can proceed without filling all the fields."`

---

### Step 3: Optional Information for the Student
- Replace subject-specific inputs with general student information:
  - **Concentration Type** (Short or Long)
  - **Break Preference** (Short or Long)
  - **Schedule** (e.g., "Mon 1-6 p.m., Tue 2-4 p.m.")
  - **Sleep Time** (e.g., "When do you sleep and wake up?")
- **Optional Step**: Users can proceed without completing all fields.
- Add a message at the top of the page:  
  > `"This step is optional. You can proceed without filling all the fields."`

---

### UI Enhancements
- Add short explanatory text to guide users through each step:
  - **Step 1**: `"Please fill out all necessary information to proceed."`
  - **Step 2**: `"Optional: Add details for each subject to customize your study plan."`
  - **Step 3**: `"Optional: Add your general information to optimize the plan for you."`
- Use button colors or tooltips to visually indicate mandatory vs. optional steps for better clarity.
- Increase the size of the `Subject-Specific Notes` input field to make it more user-friendly for detailed notes.

---

## Expected Outcome
- Improved user experience with clear separation of required and optional steps.
- Streamlined input collection process for both subject-specific and general student information.
- Enhanced usability for fields that may require more detailed input, such as `Subject-Specific Notes`.

Can you give me additional review or suggestion about this?

**Comment by woojeonghyuk** [comment]
Clearly distinguishing between mandatory and optional steps and adding user guidance to make the input process intuitive is highly impressive.

**Comment by Inyong-Hwang** [comment]
Thank you for your issue. Too much requirement can affect boring things.

**Comment by kwonjaeuk** [comment]
Hello, thank you for posting this issue!
Your proposed multi-step input process improvement idea is clear and has great potential to enhance our UX. 
Here are a few additional suggestions:

1. Step-by-Step Messaging

Step 1: "All fields must be filled out to proceed to the next step."
→ This message could emphasize that users cannot proceed without completing all fields. Additionally, highlighting incomplete fields with a simple visual cue (e.g., a red border) could make the process more intuitive.

For Steps 2 and 3, keeping the tone friendly and reassuring can help reduce any sense of pressure. 

For example:

"This step is optional. You can skip it and move to the next step if you prefer."

2. UI/UX Enhancements

In Step 2, for the 'Subject-Specific Notes' field, expanding the input size is a great idea. Adding examples within the field (e.g., placeholder text) can further guide users.
Example: "E.g., 'I don't want to study this subject on Saturdays,' or 'I will focus on this subject 2 weeks before the exam.'"

Including a progress indicator at the bottom of the form (e.g., "Step 1 of 3") can help users better understand where they are in the process and what remains.

3. Additional Considerations

In Step 3, arranging the fields in a logical order could improve the flow. For example, simpler fields like "Concentration Type" and "Break Preference" can be placed first, followed by more detailed fields like "Schedule" and "Sleep Time."
Adding a clear "Skip" button for the optional steps can make it easier for users to move forward without confusion.

4. Other Suggestions

Visually distinguish mandatory and optional steps by using different button styles, colors, or headings.
For optional steps, emphasize the flexibility by using bold or underlined text in the explanatory message to make it more noticeable.

If this proposal moves forward, I’d be happy to provide more specific feedback as needed. Let me know if there are any other concerns or ideas you'd like to discuss. Thank you 😊

**Comment by Inyong-Hwang** [comment]
I completely reflect your requirement!! Thank you guys for your detailed reviews. 💯 :)

**Comment by JunheePark0224** [comment]
Thanks. This issue is solved from CONTRIBUTORS! Always appreciate for your contribution.
